### PR TITLE
Fix the protocol error that occurs in XMLParser(contentsOf:) by avoiding it

### LINKED ISSUE #9: Protocol not available bug
Cannot get xml data because of an error in the code that fetches it.

### PR DESCRIPTION
**Pull request by porglezomp**
Fix #9

### CODE REVIEW

File: umich-dining/DiningHall.swift [hunk 1]
```diff
@@ -44,19 +44,21 @@ class DiningHall {
...
         if let date = date {
             urlString += "&date=\(date)"
         }
         guard let url = URL(string: urlString)
             else { return nil }
-        
-        guard let xml = XMLParser(contentsOf: url)
+        guard let data = try? Data(contentsOf: url)
             else { return nil }
+        print("\(String(data: data, encoding: .utf8))")
```
Comment (OkayHughes) [inline umich-dining/DiningHall.swift:55]: Eh

**Review by OkayHughes — APPROVED** [review]
